name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.x'
          channel: 'stable'
      
      - name: Check Flutter version
        run: flutter --version
      
      - name: Run simple tests
        run: |
          mkdir -p test
          echo 'import "package:flutter_test/flutter_test.dart"; void main() { test("Simple test", () { expect(true, true); }); }' > test/simple_test.dart
          flutter test test/simple_test.dart 